version: "3.4"

x-mnt: &x-mnt .:/srv
x-pwd: &x-pwd /srv
x-env: &x-env
  DB_HOST: db
  HOME: /srv
  COMPOSER_HOME: /srv/.composer
  YARN_CACHE_FOLDER: /srv/.yarn

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - *x-mnt
      - ./docker/nginx/host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${PORT:-80}:80"
  db:
    image: mariadb:10.3
    volumes:
      - database:/var/lib/mysql
      - ./docker/mariadb/mnlab.sql:/docker-entrypoint-initdb.d/mnlab.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    volumes:
      - *x-mnt
    environment:
      <<: *x-env
    user: $UID
    working_dir: *x-pwd
    command: ./docker/php/start
  yarn:
    image: node:8-alpine
    volumes:
      - *x-mnt
    environment:
      <<: *x-env
    user: $UID
    working_dir: *x-pwd
    command: sh -c "yarn && yarn run watch"

volumes:
  database:
