version: "3.4"

x-env: &x-env
  HOME: /srv
  COMPOSER_HOME: /srv/.composer
  YARN_CACHE_FOLDER: /srv/.yarn

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - .:/srv
      - ./docker/nginx/host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: mariadb:10.3
    volumes:
      - database:/var/lib/mysql
      - ./docker/mariadb/mnlab.sql:/docker-entrypoint-initdb.d/mnlab.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    volumes:
      - .:/srv
    environment:
      <<: *x-env
    user: nobody
    working_dir: /srv
    command: ./docker/php/start
  yarn:
    image: node:8-alpine
    volumes:
      - .:/srv
    environment:
      <<: *x-env
    user: nobody
    working_dir: /srv
    command: sh -c "yarn && yarn run watch"

volumes:
  database:
