version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - .:/home
      - ./docker/nginx/host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  db:
    image: mariadb:10.3
    volumes:
      - database:/var/lib/mysql
      - ./docker/mariadb/mnlab.sql:/docker-entrypoint-initdb.d/mnlab.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  php:
    build:
      context: ./docker/php
    depends_on:
      - db
    volumes:
      - .:/home
    user: '1000'
    working_dir: /home
    command: ./docker/php/start

volumes:
  database:
